services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      PUID: 1000
      PGID: 1000
      FLATNOTES_AUTH_TYPE: "none"
    volumes:
      - "/mnt/raid/flattnoes/:/data"
    ports:
      - "8080:8080"
    restart: unless-stopped

