services:
  db:
    image: postgres:13
    volumes:
      - /mnt/raid/joplin/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_USER=joplin
      - POSTGRES_DB=joplin
    restart: unless-stopped

  app:
    image: joplin/server:latest
    depends_on:
      - db
    ports:
      - "22300:22300"
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=http://your_server_ip:22300
      - DB_CLIENT=pg
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=joplin
      - DB_USER=joplin
      - DB_PASSWORD=your_password
    restart: unless-stopped
