services:
  lab:
    container_name: lab
    restart: unless-stopped
    build:
      context: ./lab/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - /home/treehouse/Documents:/home/jovyan/Documents
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              
volumes:
  ollama-data:
    
