services:
  lab:
    build:
      context: ./lab
      dockerfile: Dockerfile
    container_name: lab
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - /home/treehouse/Documents:/home/jovyan/Documents
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
