services:
  lab:
    build: .
    container_name: lab
    ports:
      - "8888:8888"
    volumes:
      - ~/Documents:/home/jovyan/
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=
      - OLLAMA_HOST=http://ollama:11434
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    depends_on:
      ollama:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama_network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
    container_name: openwebui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      ollama:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama_network

volumes:
  ollama_models:
  open-webui:

networks:
  ollama_network:
    driver: bridge
