services:
  lab:
    build:
      context: ./lab
      dockerfile: Dockerfile
    container_name: lab
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /Documents:/app
    restart: always
