services:
  lab:
    container_name: lab
    restart: unless-stopped
    build:
      context: lab/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - $HOME/.config/gh/hosts.yml:/root/.config/gh/hosts.yml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      ollama:
        condition: service_started
    networks:
      - ollama_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: 
      - /bin/sh
      - -c
      - |
        ollama serve &
        sleep 10
        ollama pull gemma3:12b
        wait
    networks:
      - ollama_network

volumes:
  ollama_models:

networks:
  ollama_network:
    driver: bridge
