services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama_network

  lab:
    build:
      context: ./lab
    container_name: lab
    stdin_open: true
    tty: true
    volumes:
      - ~/Documents:/home/Documents/
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
      - OLLAMA_HOST=http://ollama:11434
      - TERM=xterm-256color
      - SHELL=/bin/bash
    depends_on:
      ollama:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama_network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
    container_name: openwebui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      ollama:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama_network

volumes:
  ollama_models:
  open-webui:

networks:
  ollama_network:
    driver: bridge
