services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama_network

  lab:
    container_name: lab
    restart: unless-stopped
    build:
      context: lab/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - $HOME/.config/gh/hosts.yml:/root/.config/gh/hosts.yml
    environment:
      - OLLAMA_HOST=http://ollama:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      ollama:
        condition: service_started
    networks:
      - ollama_network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "8080:8080" 
    volumes:
      - openwebui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_started
    networks:
      - ollama_network

volumes:
  ollama_models:
  openwebui_data:

networks:
  ollama_network:
    driver: bridge
