services:
  monitor:
    container_name: monitor
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    privileged: true
    volumes:
      - /sys:/sys
      - /proc:/proc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
