services:
  lab:
    container_name: lab
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    volumes:
      - /home/treehouse/Documents:/home/lab/Documents
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
