services:
  lab:
    container_name: lab
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /home/treehouse/Documents:/home/lab/Documents
    networks:
      - external_network
    environment:
      - OLLAMA_HOST=http://ollama:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
            
networks:
    external_network:
      external: true
      name: ollama-net
