services:
  lab:
    container_name: lab
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    volumes:
      - $HOME/.config/gh/hosts.yml:/root/.config/gh/hosts.yml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
