services:
  lab:
    container_name: lab
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - /home/treehouse/Documents:/home/jovyan/Documents
    networks:
      - external_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
            
networks:
    external_network:
      external: true
      name: ollama-net
