services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: >
      /bin/sh -c "
        ollama serve & 
        sleep 2 && 
        ollama pull llama3 &&
        wait
      "

volumes:
  ollama_models:


