services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    networks:
      - external_network
    
networks:
  external_network:
    external: true
    name: ollama-net

volumes:
  ollama_models:


